### ISSUE TITLE
Jira Tree not working anymore...

### ISSUE THREAD

**Issue by Markus-1974** [devlauer/jiratree#2]
I still use Greasemonkey (new version compatible to new FireFox 57 (64-bit)).

When I right-click on (e.g.) MWP-11103, the context menu with 'Tree View' is displayed, but if I click on 'Tree View', nothing happens.
:-(

**Comment by devlauer** [comment]
Thanks for your information. Greasemonkey changed the way it runs userscripts in version 4 (Firefox 57). On their homepage they posted the following comment on this:

"Greasemonkey 4 is changing how it runs user scripts.  Many user scripts will continue to run as expected, but this will break some scripts. If you rely on such scripts, you might want to install Violentmonkey or Tampermonkey, both of which provide better compatibility for existing scripts."

As supposed, please switch to either tampermonkey (which is tested to be compliant with this script in firefox and chrome) or violentmonkey. I've changed the Readme.md to reflect this compatibility change.
